# Generated by Django 3.2.7 on 2021-09-27 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FakeSchemas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('delimiters', models.CharField(choices=[(',', 'Comma (,)'), (';', 'Semicolon (;)'), ('\t', 'Tab (\t)'), (' ', 'Space ( )'), ('|', 'Vertical bar (|)')], default=',', max_length=1)),
                ('quotes', models.CharField(choices=[('"', 'Double-quote (")'), ("'", "Single-quote (')")], default='"', max_length=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fake_schemas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FakeSchemasColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='column name')),
                ('data_type', models.IntegerField(choices=[(0, 'Full name'), (1, 'Job'), (2, 'Email'), (3, 'Text'), (4, 'Integer'), (5, 'Address'), (6, 'Date')], verbose_name='type')),
                ('order', models.IntegerField(blank=True, default=0)),
                ('data_range_from', models.IntegerField(blank=True, null=True, verbose_name='from')),
                ('data_range_to', models.IntegerField(blank=True, null=True, verbose_name='to')),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schema_column', to='fake_schemas.fakeschemas')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ExportedDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'processing'), (1, 'ready'), (2, 'error')], default=0)),
                ('download_link', models.URLField(blank=True, null=True)),
                ('task_id', models.IntegerField(blank=True, null=True)),
                ('schema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schemadatasets', to='fake_schemas.fakeschemas')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
